### ISSUE TITLE
Inconsistency in handling of resume/fetch with FilteringStream

### ISSUE THREAD

**Issue by Yaytay** [tsegismont/streamutils#9]
With the exception of the FilteringStream, calling resume/fetch on the stream directly calls resume/fetch on the source.
The FilteringStream goes through an InboundBuffer that doesn't directly call resume/fetch.

In all your tests you directly call fakeStream.emit(), which hides the discrepancy.

IMO a ReadStream wrapper should completely encapsulate the wrapped stream and it should not be necessary for the caller to retain any reference to the source.

Does the FilteringStream actually need to use the InboundBuffer at all?

**Comment by tsegismont** [comment]
Yes, is required to do this in order to fulfill the `ReadStream` contract.

Suppose you call `fetch` twice on the filtered stream but the source is composed of a "bad" item followed by two "good items".

If you invoke resume/fetch directly on the source, you will get only one item emitted by the filtered stream.

This is why you need some sort of buffer, which is exactly what `InboundBuffer` is designed for.
